---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the helm output (all.yaml) that was saved by the post-renderer
# This file contains the controller deployment and other helm-generated resources
resources:
  - all.yaml
  - ../base/envoy-gateway-namespace.yaml
  - ../base/envoy-internal-gateway-issuer.yaml
  - ../base/envoy-custom-proxy-config.yaml
  - ../base/envoy-gatewayclass.yaml
  - ../base/envoy-gateway.yaml
  - ../base/envoy-endpoint-policies.yaml
  - ../base/envoy-service-monitor.yaml
