---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-gateway-fabric
  namespace: prometheus
  labels:
    app.kubernetes.io/name: nginx-gateway-fabric
spec:
  namespaceSelector:
    matchNames: [nginx-gateway]
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-gateway-fabric
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
