---
site_name: Open Infrastructure
site_description: >-
  Open Infrastructure, a Rackspace solution, is a collection of open-source tools and technologies that provide a
  flexible, scalable, and cost-effective infrastructure solution for your business. This documentation provides
  information on how to deploy and manage Open-Infrastructure in your environment. It also provides information on how
  to onboard and manage your workloads on OpenStack, Kubernetes, and other open-source technologies.

site_url: https://docs.rackspacecloud.com

theme:
  name: material
  logo: assets/images/rackspace_logo-white.svg
  favicon: assets/images/pngegg.png
  icon:
    logo: logo
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: rxt
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - announce.dismiss
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.prune
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

copyright: Copyright &copy; 2024 RACKSPACE TECHNOLOGY

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/rackspace
      name: Rackspace on LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/rackspace
      name: Rackspace on X
    - icon: fontawesome/brands/github
      link: https://github.com/rackerlabs
      name: Rackspace on github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/2mN5yZvV3a
      name: Rackspace on Discord
    - icon: fontawesome/solid/blog
      link: https://blog.rackspacecloud.com/

extra_css:
  - overrides/stylesheets/adr.css

plugins:
  - search
  - swagger-ui-tag
  - mkdocs-material-adr/adr
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      restrict_base_path: false

repo_name: rackerlabs/genestack
repo_url: https://github.com/rackerlabs/genestack
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/docs"

nav:
  - Welcome: index.md
  - Overview:
      - Architecture: genestack-architecture.md
      - Components: genestack-components.md
  - Quickstart:
      - Building Virtual Environments: build-test-envs.md
      - Simple Setup: quickstart.md
  - Deployment Guide:
      - What is Genestack?: deployment-guide-welcome.md
      - Getting Started: genestack-getting-started.md
      - Open Infrastructure:
          - Kubernetes:
              - k8s-overview.md
              - Providers:
                  - Kubespray: k8s-kubespray.md
              - Post Deployment:
                  - Kubernetes Labels: k8s-labels.md
                  - Kubernetes Dashboard: k8s-dashboard.md
                  - Kubernetes Taint: k8s-taint.md
              - Retrieve kube config: k8s-config.md
              - Prometheus: prometheus.md
              - OpenStack Preparations: openstack-helm-make.md
          - Storage:
              - storage-overview.md
              - Ceph Internal: storage-ceph-rook-internal.md
              - Ceph External: storage-ceph-rook-external.md
              - NFS External: storage-nfs-external.md
              - TopoLVM: storage-topolvm.md
              - External Storage CSI: storage-external-block.md
          - Secrets:
              - vault.md
              - Vault Operator: vault-secrets-operator.md
              - Sealed Secrets: sealed-secrets.md
          - Infrastructure:
              - infrastructure-overview.md
              - Namespace: infrastructure-namespace.md
              - Ingress: infrastructure-ingress.md
              - LetsEncrypt: infrastructure-letsencrypt.md
              - MariaDB:
                  - infrastructure-mariadb.md
              - RabbitMQ:
                  - infrastructure-rabbitmq.md
              - Memcached: infrastructure-memcached.md
              - Libvirt: infrastructure-libvirt.md
              - OVN: infrastructure-ovn-setup.md
              - MetalLB: infrastructure-metallb.md
              - Gateway API: infrastructure-gateway-api.md
              - Loki: infrastructure-loki.md
          - OpenStack:
              - openstack-overview.md
              - OpenStack Services:
                  - Keystone: openstack-keystone.md
                  - Glance: openstack-glance.md
                  - Heat: openstack-heat.md
                  - Cinder: openstack-cinder.md
                  - Compute Kit: openstack-compute-kit.md
                  - Dashboards:
                      - Horizon: openstack-horizon.md
                      - skyline: openstack-skyline.md
                  - Octavia: openstack-octavia.md
                  - Metering:
                    - PostgreSQL: infrastructure-postgresql.md
                    - Gnocchi: openstack-gnocchi.md
                    - Ceilometer: openstack-ceilometer.md
          - Monitoring:
              - Monitoring Overview: prometheus-monitoring-overview.md
              - Getting Started: monitoring-getting-started.md
              - Grafana: grafana.md
              - Kube-OVN Monitoring: prometheus-kube-ovn.md
              - RabbitMQ Exporter: prometheus-rabbitmq-exporter.md
              - Memcached Exporter: prometheus-memcached-exporter.md
              - Postgres Exporter: prometheus-postgres-exporter.md
              - Openstack Exporter: prometheus-openstack-metrics-exporter.md
              - Blackbox Exporter: prometheus-blackbox-exporter.md
              - Custom Node Metrics: prometheus-custom-node-metrics.md
              - Alert Manager Examples:
                  - alertmanager-encore.md
                  - alertmanager-slack.md
  - Operational Guide:
      - Running Genestack Upgrade: genestack-upgrade.md
      - Running Kubespray Upgrade: k8s-kubespray-upgrade.md
      - Infrastructure:
          - Etcd Backup: etcd-backup.md
          - OVN introduction: ovn-intro.md
          - OVN troubleshooting: ovn-troubleshooting.md
          - OVN traffic flow introduction: ovn-traffic-flow-intro.md
          - OVN Database Backup: infrastructure-ovn-db-backup.md
          - MariaDB Operations: infrastructure-mariadb-ops.md
      - OpenStack:
          - Generating Clouds YAML: openstack-clouds.md
          - Keystone Federation to Rackspace: openstack-keystone-federation.md
          - Keystone Readonly Users: openstack-keystone-readonly.md
          - Nova Flavor Creation: openstack-flavors.md
          - Nova CPU Allocation Ratio: openstack-cpu-allocation-ratio.md
          - Creating Networks: openstack-neutron-networks.md
          - Glance Images Creation: openstack-glance-images.md
      - Building Local Images: build-local-images.md
      - Working Locallly With Docs: mkdocs-howto.md
      - Third Party Tools:
          - OSIE: extra-osie.md
  - Cloud Onboarding:
      - Cloud Onboarding Welcome: cloud-onboarding-welcome.md
      - Openstack Deploying CLI Tools: openstack-deploy-cli.md
      - Openstack Security Groups: openstack-security-groups.md
      - Openstack Floating Ips: openstack-floating-ips.md
      - Openstack Keypairs: openstack-keypairs.md
      - Openstack Servers: openstack-servers.md
      - Openstack Images: openstack-images.md
      - Openstack Swift: storage-swift-object-store.md
      - Openstack Snapshot: openstack-snapshot.md
      - Openstack Volumes: openstack-volumes.md
  - Blog: https://blog.rackspacecloud.com/
