---
site_name: Open Infrastructure
site_description: >-
  Open Infrastructure, a Rackspace solution, is a collection of open-source tools and technologies that provide a
  flexible, scalable, and cost-effective infrastructure solution for your business. This documentation provides
  information on how to deploy and manage Open-Infrastructure in your environment. It also provides information on how
  to onboard and manage your workloads on OpenStack, Kubernetes, and other open-source technologies.

site_url: https://docs.rackspacecloud.com

theme:
  name: material
  logo: assets/images/rackspace_logo-white.svg
  favicon: assets/images/pngegg.png
  icon:
    logo: logo
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: rxt
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - announce.dismiss
    - header.autohide
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.prune
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

copyright: Copyright &copy; 2024 RACKSPACE TECHNOLOGY

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/rackspace
      name: Rackspace on LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/rackspace
      name: Rackspace on X
    - icon: fontawesome/brands/github
      link: https://github.com/rackerlabs
      name: Rackspace on github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/2mN5yZvV3a
      name: Rackspace on Discord
    - icon: fontawesome/solid/blog
      link: https://blog.rackspacecloud.com/

extra_css:
  - overrides/stylesheets/adr.css

plugins:
  - search
  - swagger-ui-tag
  - mkdocs-material-adr/adr
  - glightbox

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      restrict_base_path: false

repo_name: rackerlabs/genestack
repo_url: https://github.com/rackerlabs/genestack
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/docs"

nav:
  - Welcome: index.md
  - Overview:
      - Architecture: genestack-architecture.md
      - Components: genestack-components.md
      - Swift Object Storage: openstack-object-storage-swift.md
  - Deployment Guide:
      - What is Genestack?: deployment-guide-welcome.md
      - Getting Started:
          - Building Virtual Environments: build-test-envs.md
          - Getting the code: genestack-getting-started.md
      - Open Infrastructure:
          - Kubernetes:
              - k8s-overview.md
              - Providers:
                  - Kubespray: k8s-kubespray.md
              - Post Deployment:
                  - Kubernetes Labels: k8s-labels.md
                  - Kubernetes Dashboard: k8s-dashboard.md
                  - Kubernetes Taint: k8s-taint.md
              - Retrieve kube config: k8s-config.md
              - Prometheus: prometheus.md
              - OpenStack Preparations: openstack-helm-make.md
          - Storage:
              - storage-overview.md
              - Ceph Internal: storage-ceph-rook-internal.md
              - Ceph External: storage-ceph-rook-external.md
              - NFS External: storage-nfs-external.md
              - TopoLVM: storage-topolvm.md
              - External Storage CSI: storage-external-block.md
          - Secrets:
              - Sealed Secrets: sealed-secrets.md
          - Infrastructure:
              - infrastructure-overview.md
              - Namespace: infrastructure-namespace.md
              - MetalLB: infrastructure-metallb.md
              - Gateway API: infrastructure-gateway-api.md
              - MariaDB:
                  - infrastructure-mariadb.md
              - RabbitMQ:
                  - infrastructure-rabbitmq.md
              - Memcached: infrastructure-memcached.md
              - Libvirt: infrastructure-libvirt.md
              - OVN: infrastructure-ovn-setup.md
              - Loki: infrastructure-loki.md
          - OpenStack:
              - openstack-overview.md
              - OpenStack Services:
                  - Keystone: openstack-keystone.md
                  - Glance: openstack-glance.md
                  - Heat: openstack-heat.md
                  - Barbican: openstack-barbican.md
                  - Block Storage:
                      - Cinder: openstack-cinder.md
                      - LVM iSCSI: openstack-cinder-lvmisci.md
                      - FIPS Cinder Encryption: openstack-cinder-fips-encryption.md
                  - Compute Kit:
                      - Compute Overview: openstack-compute-kit.md
                      - Secrets: openstack-compute-kit-secrets.md
                      - Placement: openstack-compute-kit-placement.md
                      - Nova: openstack-compute-kit-nova.md
                      - Neutron: openstack-compute-kit-neutron.md
                  - Dashboards:
                      - Horizon: openstack-horizon.md
                      - skyline: openstack-skyline.md
                  - Octavia: openstack-octavia.md
                  - Magnum: openstack-magnum.md
                  - Metering:
                      - PostgreSQL: infrastructure-postgresql.md
                      - Gnocchi: openstack-gnocchi.md
                      - Ceilometer: openstack-ceilometer.md
          - Monitoring:
              - Monitoring Overview: prometheus-monitoring-overview.md
              - Getting Started: monitoring-getting-started.md
              - Grafana: grafana.md
              - Kube-OVN Monitoring: prometheus-kube-ovn.md
              - RabbitMQ Exporter: prometheus-rabbitmq-exporter.md
              - Memcached Exporter: prometheus-memcached-exporter.md
              - MariaDB Exporter: prometheus-mysql-exporter.md
              - Postgres Exporter: prometheus-postgres-exporter.md
              - Openstack Exporter: prometheus-openstack-metrics-exporter.md
              - Blackbox Exporter: prometheus-blackbox-exporter.md
              - Pushgateway: prometheus-pushgateway.md
              - Custom Node Metrics: prometheus-custom-node-metrics.md
              - Alert Manager Examples:
                  - alertmanager-encore.md
                  - alertmanager-slack.md
  - Operational Guide:
      - Supporting multi-region Genestack: multi-region-support.md
      - Running Genestack Upgrade: genestack-upgrade.md
      - Running Kubespray Upgrade: k8s-kubespray-upgrade.md
      - Infrastructure:
          - Etcd Backup: etcd-backup.md
          - OVN introduction: ovn-intro.md
          - OVN troubleshooting: ovn-troubleshooting.md
          - OVN traffic flow introduction: ovn-traffic-flow-intro.md
          - OVN Database Backup: infrastructure-ovn-db-backup.md
          - OVN Monitoring introduction: ovn-monitoring-introduction.md
          - MariaDB Operations: infrastructure-mariadb-ops.md
          - Adding New Node: adding-new-node.md
          - Host Aggregates: openstack-host-aggregates.md
      - Third Party Tools:
          - OSIE: extra-osie.md
      - OpenStack:
          - CLI Access:
              - Generating Clouds YAML: openstack-clouds.md
          - Compute:
              - Nova Flavor Creation: openstack-flavors.md
              - Nova CPU Allocation Ratio: openstack-cpu-allocation-ratio.md
              - Nova PCI Passthrough: openstack-pci-passthrough.md
          - Images:
              - Glance Images Creation: openstack-glance-images.md
          - Identity:
              - Keystone Federation to Rackspace: openstack-keystone-federation.md
              - Keystone Readonly Users: openstack-keystone-readonly.md
          - Networking:
              - Creating Networks: openstack-neutron-networks.md
          - Magnum:
              - Creating kubernetes clusters: magnum-kubernetes-cluster-setup-guide.md
          - Octavia:
              - Creating Cloud Load Balancers: octavia-loadbalancer-setup-guide.md
          - Object Storage:
              - Operating Swift Object Storage: openstack-swift-operators-guide.md
          - Service Overrides: openstack-service-overrides.md
      - Working locally With Docs: mkdocs-howto.md
  - Cloud Onboarding:
      - Cloud Onboarding Welcome: cloud-onboarding-welcome.md
      - Openstack Installing CLI Tools: openstack-deploy-cli.md
      - OpenStack Getting Started: openstack-getting-started-cli.md
      - Openstack Security Groups: openstack-security-groups.md
      - Openstack Floating Ips: openstack-floating-ips.md
      - Openstack Keypairs: openstack-keypairs.md
      - Openstack Servers: openstack-servers.md
      - Openstack Routers: openstack-router.md
      - Openstack Images: openstack-images.md
      - Openstack Object Store Swift CLI: storage-object-store-swift-cli.md
      - Openstack Object Store Openstack CLI: storage-object-store-openstack-cli.md
      - Openstack Object Store Skyline GUI: storage-object-store-skyline-gui.md
      - Openstack Snapshot: openstack-snapshot.md
      - Openstack Volumes: openstack-volumes.md
      - Openstack Load Balancers: openstack-load-balancer.md
      - Openstack Networks: openstack-networks.md
  - Blog: https://blog.rackspacecloud.com/
  - Status: api-status.md
