---
sortOptions:
  order: fifo
resources:
  - nova-mariadb-database.yaml
  - nova-rabbitmq-queue.yaml
  - all.yaml
  - hpa-nova-api-metadata.yaml
  - hpa-nova-api-osapi.yaml
  - hpa-nova-conductor.yaml
  - hpa-nova-novncproxy.yaml
  - hpa-nova-scheduler.yaml
  - hpa-nova-compute-ironic.yaml
  - policies.yaml
  - static-vendordata-configmap.yaml
