sortOptions:
  order: fifo

resources:
  - all.yaml

patches:
  - path: nginx-conf-override.yaml
    target:
      kind: Deployment
      name: nginx-gateway-fabric
      namespace: nginx-gateway
configMapGenerator:
  - name: nginx-conf-override
    namespace: nginx-gateway
    options:
      disableNameSuffixHash: true
    files:
      - files/nginx.conf
