sortOptions:
  order: fifo

commonLabels:
  app: ovn-backup
namespace: kube-system
secretGenerator:
  - name: ovn-backup-swift-tempauth-account
    envs:
      - swift-tempauth.env
configMapGenerator:
  - name: ovn-backup-script
    files:
    - ovn-backup.sh
  - name: ovn-backup-config
    envs:
    - ovn-backup.config

resources:
  - ovn-backup.yaml
