sortOptions:
  order: fifo

resources:
  - ../base

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: nova-api-metadata
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: nova-api-osapi
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: nova-conductor
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: nova-novncproxy
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
      name: nova-scheduler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
