---

- name: Copy Multipath mpctl file to compute nodes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/monitor_setup/files/mpctl"
    dest: /opt/monitor/bin/mpctl
    owner: root
    group: root
    mode: "0755"
  when: monitor_compute.on_off_status == 'on' and monitor_compute.multipath_check == 'on'


- name: Copy and interpolate mpctl.ini config file
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/monitor_setup/templates/mpctl.ini.j2"
    dest: /opt/monitor/conf/mpctl.ini
    owner: root
    group: root
    mode: "0640"
  when: monitor_compute.on_off_status == 'on' and monitor_compute.multipath_check == 'on'


- name: Create /etc/cron.d/flex-monitor-multipath
  ansible.builtin.cron:
    name: "multipath monitor"
    minute: "*/3"
    user: root
    job: "/opt/monitor/bin/mpctl --conf /opt/monitor/conf/mpctl.ini check > /dev/null 2>&1"
    cron_file: flex-monitor-multipath
    state: present
  when: monitor_compute.on_off_status == 'on' and monitor_compute.multipath_check == 'on'


- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/cron.d/flex-monitor-multipath
    owner: root
    group: root
    mode: '0755'
  when: monitor_compute.on_off_status == 'on' and monitor_compute.multipath_check == 'on'


- name: Removes /etc/cron.d/flex-monitor-multipath
  ansible.builtin.cron:
    name: "multipath monitor"
    cron_file: flex-monitor-multipath
    state: absent
  when: monitor_compute.on_off_status == 'off' or monitor_compute.multipath_check == 'off'
