additionalPrometheusRulesMap:
  mariadb-alerts:
    groups:
      - name: mariadb-alerts
        rules:
          - alert: MariaDBDown
            expr: mysql_up != 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: MariaDB not up and running, immediate attention is required.
              description: "MariaDB {{$labels.job}} on {{$labels.instance}} is not up."
          - alert: MysqlTooManyConnections(>80%)
            expr: max_over_time(mysql_global_status_threads_connected[1m]) / mysql_global_variables_max_connections * 100 > 80
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: MySQL too many connections (> 80%) (instance {{ $labels.instance }})
              description: "More than 80% of MySQL connections are in use on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          - alert: MariaDBReplicationErrors
            expr: mysql_slave_status_last_sql_errno != 0 or mysql_slave_status_last_io_errno != 0 or mysql_slave_status_last_errno != 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: MariaDB is reporting replication errors from {{$labels.instance}}, immediate attention is required.
              description: "MariaDB {{$labels.job}} on {{$labels.instance}} is reporting replication errors."
          - alert: MysqlSlaveReplicationLag
            expr: ( (mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay) and ON (instance) mysql_slave_status_master_server_id > 0 ) > 30
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: MySQL Slave replication lag (instance {{ $labels.instance }})
              description: "MySQL replication lag on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
          - alert: MysqlSlowQueries
            expr: increase(mysql_global_status_slow_queries[1m]) > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "MySQL slow queries (instance {{ $labels.instance }})"
              description: |
                MySQL server has some new slow queries.
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
          - alert: MysqlRestarted
            expr: mysql_global_status_uptime < 60
            for: 0m
            labels:
              severity: info
            annotations:
              summary: "MySQL restarted (instance {{ $labels.instance }})"
              description: |
                MySQL has just been restarted, less than one minute ago on {{ $labels.instance }}.
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
