sortOptions:
  order: fifo

resources:
  - "../base"

patches:
  - target:
      kind: MariaDB
      name: mariadb-cluster
    patch: |-
      - op: add
        path: /spec/galera
        value: {"enabled": true, "replicaThreads": 4}
      - op: replace
        path: /spec/replication/enabled
        value: false
      - op: replace
        path: /spec/myCnf
        value: |
          [mariadb]
          bind_address=0.0.0.0
          binlog_format=ROW
          default_storage_engine=InnoDB
          ignore_db_dirs=lost+found
          innodb_autoinc_lock_mode=2
          innodb_buffer_pool_size=4G
          innodb_doublewrite=1
          innodb_file_per_table=1
          innodb_flush_log_at_trx_commit=0
          innodb_flush_method=O_DIRECT
          innodb_io_capacity=500
          innodb_log_buffer_size=128M
          innodb_log_file_size=1G
          innodb_old_blocks_time=1000
          innodb_read_io_threads=8
          innodb_rollback_on_timeout=1
          innodb_stats_on_metadata=0
          innodb_write_io_threads=8
          interactive_timeout=360
          max_allowed_packet=256M
          max_connect_errors=1000000
          max_connections=10240
          max_heap_table_size=32M
          net_read_timeout=360
          net_write_timeout=360
          open_files_limit=164679
          performance_schema=ON
          query_cache_size=0
          query_cache_type=OFF
          skip_name_resolve
          table_definition_cache=1024
          table_definition_cache=4096
          table_open_cache=10240
          thread_cache_size=50
          tmp_table_size=32M
          wait_timeout=360
          wsrep_provider_options="gcache.size=1024M;gcs.fc_limit=64"
          wsrep_retry_autocommit=3
          wsrep_slave_threads=4
