sortOptions:
  order: fifo

resources:
  - ns-topolvm.yaml

helmCharts:
  - name: topolvm
    releaseName: topolvm
    valuesInline:
      controller:
        replicaCount: 1
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
      scheduler:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
      cert-manager:
        enabled: false
      storageClasses:
        - name: general  # Defines name of storage class.
          storageClass:
            fsType: xfs  # Supported filesystems are: ext4, xfs, and btrfs.
            # reclaimPolicy
            reclaimPolicy:  # Delete
            # Additional annotations
            annotations: {}
            # Default storage class for dynamic volume provisioning
            # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
            isDefaultClass: true
            # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
            volumeBindingMode: Immediate
            # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
            allowVolumeExpansion: true
            additionalParameters:
              topolvm.io/device-class: "general"
            # mount options
            mountOptions: []
      # lvmd service
      lvmd:
        # lvmd.managed -- If true, set up lvmd service with DaemonSet.
        managed: true
        # lvmd.socketName -- Specify socketName.
        socketName: /run/topolvm/lvmd.sock
        # lvmd.deviceClasses -- Specify the device-class settings.
        deviceClasses:
          - name: general
            volume-group: vg-general
            default: true
            spare-gb: 10
    includeCRDs: true
    namespace: topolvm-system
    repo: https://topolvm.github.io/topolvm
