sortOptions:
  order: fifo

resources:
  - glance-mariadb-database.yaml
  - glance-rabbitmq-queue.yaml
  - all.yaml
  - hpa-glance-api.yaml
  - glance-routes.yaml
  - client-settings.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: glance-images
    patch: |-
      - op: replace
        path: /spec/accessModes
        value: ["ReadWriteMany"]
