---
sortOptions:
  order: fifo
resources:
  - glance-mariadb-database.yaml
  - glance-rabbitmq-queue.yaml
  - all.yaml
  - hpa-glance-api.yaml
  - policies.yaml

patches:
  - target:
      kind: ConfigMap
      name: glance-bin
    path: patch-glance-bin.yaml
