sortOptions:
  order: fifo

resources:
  - namespace.yaml

namespace: sealed-secrets
helmGlobals:
  chartHome: ../charts/
helmCharts:
- name: sealed-secrets
  includeCRDs: true
  releaseName: sealed-secrets
  valuesFile: values.yaml
  version: 2.14.2
  repo: https://bitnami-labs.github.io/sealed-secrets
