sortOptions:
  order: fifo

resources:
  - './namespace.yaml'
  - './gatewayclass.yaml'

namespace: envoy-gateway-system
helmGlobals:
  chartHome: ../../../submodules/envoyproxy-gateway/charts/
helmCharts:
- name: gateway-helm
  valuesFile: values.yaml
  includeCRDs: true
  releaseName: envoyproxy-gateway
