sortOptions:
  order: fifo

resources:
  - "../base"

patches:
  - target:
      kind: MariaDB
      name: mariadb-cluster
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/replication/enabled
        value: false
