helmCharts:
  - name: mariadb-operator
    repo: https://mariadb-operator.github.io/mariadb-operator
    releaseName: mariadb-operator
    valuesInline:
      webhook:
        cert:
          certManager:
            enabled: true
    includeCRDs: true
    namespace: openstack
