---
sortOptions:
  order: fifo

resources:
  - all.yaml

patches:
  - path: kube-ovn-nodeSelector-patch.yaml
    target:
      kind: Deployment
      name: kube-ovn-controller
      namespace: kube-system
  - path: patch-ovn-tls-mount.yaml
    target:
      kind: Deployment
      name: ovn-central
      namespace: kube-system
