---
sortOptions:
  order: fifo

images:
  - name: image-kubernetes-entrypoint-init
    newName: ghcr.io/rackerlabs/genestack-images/kubernetes-entrypoint
    newTag: latest
  - name: image-octavia-ovn
    newName: ghcr.io/rackerlabs/genestack-images/octavia
    newTag: 2024.1-latest

resources:
  - octavia-mariadb-database.yaml
  - octavia-rabbitmq-queue.yaml
  - all.yaml
  - hpa-octavia-api.yaml
  - hpa-octavia-worker.yaml
  - policies.yaml

# To run the OVN driver, the octavia-api container must have an agent container within the same pod.
patches:
  - target:
      kind: Secret
      name: octavia-etc
    patch: |-
      - op: add
        path: /data/policy.yaml
        value: LS0tCm9zX2xvYWQtYmFsYW5jZXJfYXBpOmZsYXZvci1wcm9maWxlOmdldF9vbmU6IHJ1bGU6bG9hZC1iYWxhbmNlcjpyZWFkCm9zX2xvYWQtYmFsYW5jZXJfYXBpOmZsYXZvci1wcm9maWxlOmdldF9hbGw6IHJ1bGU6bG9hZC1iYWxhbmNlcjpyZWFkCm9zX2xvYWQtYmFsYW5jZXJfYXBpOmxvYWRiYWxhbmNlcjpwdXRfZmFpbG92ZXI6ICJydWxlOmxvYWQtYmFsYW5jZXI6YWRtaW4gb3IgcnVsZTpsb2FkLWJhbGFuY2VyOm1lbWJlcl9hbmRfb3duZXIiCm9zX2xvYWQtYmFsYW5jZXJfYXBpOmFtcGhvcmE6cHV0X2ZhaWxvdmVyOiAicnVsZTpsb2FkLWJhbGFuY2VyOmFkbWluIG9yIHJ1bGU6bG9hZC1iYWxhbmNlcjptZW1iZXJfYW5kX293bmVyIgoK
  - target:
      kind: Deployment
      name: octavia-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          runAsUser: 0
  - target:
      kind: Deployment
      name: octavia-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/-
        value:
          command:
            - octavia-driver-agent
            - --config-dir
            - /etc/octavia/octavia.conf
          image: image-octavia-ovn
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          securityContext:
            runAsUser: 0
          name: octavia-agent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: pod-etc-octavia
              mountPath: /etc/octavia
            - name: octavia-bin
              mountPath: /tmp/octavia-api.sh
              subPath: octavia-api.sh
              readOnly: true
            - name: octavia-etc
              mountPath: /etc/octavia/octavia.conf
              subPath: octavia.conf
              readOnly: true
            - name: octavia-etc
              mountPath: /etc/octavia/logging.conf
              subPath: logging.conf
              readOnly: true
            - mountPath: /var/run/octavia
              name: pod-run-octavia
